### ISSUE TITLE
Not working in the latest Kotlin version.

### ISSUE THREAD

**Issue by Scottyd944** [mbieniek/FacebookImagePicker#12]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gdncapp, PID: 29987
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/ObservableOnSubscribe;
        at com.mbieniek.facebookimagepicker.facebook.controllers.FacebookAlbumPickerController.<init>(FacebookAlbumPickerController.kt:33)
        at com.mbieniek.facebookimagepicker.facebook.FacebookAlbumPickerActivity.<init>(FacebookAlbumPickerActivity.kt:29)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3007)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3256)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.reactivex.ObservableOnSubscribe" on path: DexPathList[[zip file "/data/app/com.gdncapp-rJoBTsvQt_lPH7Yha5XapQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.gdncapp-rJoBTsvQt_lPH7Yha5XapQ==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

**Comment by akhilkateja123** [comment]
Update build.gradle with following dependencies:
    implementation 'io.reactivex.rxjava2:rxjava:2.2.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
