### ISSUE TITLE
java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; 

### ISSUE THREAD

**Issue by tijot123** [mbieniek/FacebookImagePicker#8]
java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.appbazooka.floatalbums-EuHOuVUkcy1JT7eA8nemrA==/split_lib_dependencies_apk.apk!classes2.dex)
        at com.mbieniek.facebookimagepicker.facebook.adapters.FacebookAlbumAdapter$FacebookAlbumViewHolder.bind(FacebookAlbumAdapter.kt:69)
        at com.mbieniek.facebookimagepicker.facebook.adapters.FacebookAlbumAdapter.onBindViewHolder(FacebookAlbumAdapter.kt:41)
        at com.mbieniek.facebookimagepicker.facebook.adapters.FacebookAlbumAdapter.onBindViewHolder(FacebookAlbumAdapter.kt:31)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6193)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6193)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6193)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6193)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6193)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6193)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7191)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
        at android.view.Choreographer.doCallbacks(Choreographer.java:816)
        at android.view.Choreographer.doFrame(Choreographer.java:751)
2019-02-28 14:21:47.309 28364-28364/com.appbazooka.floatalbums E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mbieniek** [comment]
Try adding this to your build.gradle:

implementation 'com.squareup.picasso:picasso:2.71828'

**Comment by tijot123** [comment]
after adding this to my gradle files this happened. i am using glide so can
u upload nest version..i have seen your code in git it contains methods to
find which loader is used glide or picasso..please release that version
immediately

**Comment by mbieniek** [comment]
That code should be in version 1.0.2 or 1.0.3. What version are you using?

**Comment by tijot123** [comment]
i have seen that u have released new version.currently i have issues with
1.0.1..

**Comment by tijot123** [comment]
i will update to new version

**Comment by tijot123** [comment]
new problem facing now is
ERROR: Failed to resolve:
com.github.mbieniek.facebookimagepicker:facebookimagepicker:1.0.3
Show in Project Structure dialog
Affected Modules: app

**Comment by mbieniek** [comment]
Does 1.0.4 work?

**Comment by mbieniek** [comment]
Ah I fixed the issue with Maven, you should be able to pull 1.0.3 or 1.0.2 now.

**Comment by tijot123** [comment]
In version 1.0.3 on click images 


2019-03-11 19:41:14.821 29794-29794/com.appbazooka.floatalbums E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appbazooka.floatalbums, PID: 29794
    kotlin.UninitializedPropertyAccessException: lateinit property menu has not been initialized
        at com.mbieniek.facebookimagepicker.facebook.FacebookImagePickerActivity.getMenu(FacebookImagePickerActivity.kt:28)
        at com.mbieniek.facebookimagepicker.facebook.FacebookImagePickerActivity$onCreate$1.imageSelectedListUpdated(FacebookImagePickerActivity.kt:38)
        at com.mbieniek.facebookimagepicker.facebook.adapters.FacebookImageAdapter$onBindViewHolder$1.imageClicked(FacebookImageAdapter.kt:45)
        at com.mbieniek.facebookimagepicker.facebook.adapters.FacebookImageAdapter$FacebookImageViewHolder$bind$1.onClick(FacebookImageAdapter.kt:73)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:782)
        at android.view.View$PerformClick.run(View.java:25945)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
